language: node_js
node_js:
- 8
deploy:
  provider: npm
  email: david.beale@bealearts.co.uk
  api_key:
    secure: etEUjy6s6RJAKG1YRS5/ib+f7dmy6GccJEMz7Fp2djZai9tCB5GNsT0pAgGGnh38XDzwuVWh1bCLcido37VhNZD+lXnasdZwmjvHLrqPKi7OwMjO7xi4mxxc3znhZWPuIL5k+bZPHlyNQIZf5I+fmkSfHiVHvYzYII4XltdjIZWFhhajeYfuz6eDUPJgSfjWJqr4klZ6znl1XVtbqRfSdbDY2uH0xmr/doIzW5hCseg5YA+XfgWIdOVsyhsLf/53rxm1DfljV0TY3Oim6obgJYVvVbHQVbpypjJifs+Dkebx9QdoCedQMNjZaDtg6Jl9VMa+nBQ7aaFbsHoFO72ecJNcEbw3yw5+0p7/Y2zY7ezGFoEjzTMUTzIhGd0ZB+FsVN9klzISFoG2obuOrBZ4Ojdq49QM6uNRx289CDY/ly5QnOe8e+h3TyNUk3FySLvOe1jmltBzKbjnBR/djDdJges1ExgQsW0lxilIAm6b7/pmSSgbjO3q2rhpbAoTeyPZ2iDxcYYhHMassIMB2sOomz3Dkl6ZpIzSB3zHeQvD6E5kFwGXvlhQWoFqxbDIVOrU9I+GKZSCMJa/wdK8duoDgvRbUUUIAAHPXIGF2n7v5VCkEoMyDBZLbCcHUBF53wRlnLcwXplE407Py5kF2woywTJMmZCY8RSGJwSWsgwEZg4=
  on:
    tags: true
    repo: bealearts/micro-basic-auth
